/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
}
export type Category = { 'clothing' : null } |
  { 'sports' : null } |
  { 'homeGarden' : null } |
  { 'electronics' : null };
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : Time,
  'totalAmount' : number,
  'shippingAddress' : Address,
  'customerId' : string,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export interface OrderInput {
  'customerName' : string,
  'shippingAddress' : Address,
  'customerId' : string,
  'items' : Array<OrderItemInput>,
  'customerEmail' : string,
}
export interface OrderItem {
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : number,
}
export interface OrderItemInput { 'productId' : bigint, 'quantity' : bigint }
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'supplierName' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'imageUrl' : [] | [ExternalBlob],
  'category' : Category,
  'price' : number,
}
export interface ProductInput {
  'inStock' : boolean,
  'supplierName' : string,
  'name' : string,
  'description' : string,
  'category' : Category,
  'price' : number,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<[ProductInput], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'filterProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductsByIds' : ActorMethod<[Array<bigint>], Array<Product>>,
  'initializeSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[OrderInput], bigint>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], undefined>,
  'uploadProductImage' : ActorMethod<[bigint, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];